/**
 * Builds {@link Opportunity} objects.
 */
public inherited sharing class OpportunityFactory {
  /**
   * Creates premium {@link Opportunity} records based on the input list of {@link Opportunity} records.
   *
   * TODO: resume here - building premium opportunities, then writing tests
   *  - assign it to the existing opp owner
   *  - use the premium product list in the constants file
   */
  public List<Opportunity> createPremiumOpportunities(
    List<Opportunity> opportunities
  ) {
    return new List<Opportunity>();
  }
}